ccnmtl/pump

pump/main/criteria.py
pump/main/tests/test_criteria.py
pump/templates/main/index.html

Updating text, videos, and passing criteria

---

requirements.txt

remove feedparser

---

pump/settings_shared.py
requirements.txt

remove tagging

---

pump/settings_shared.py
requirements.txt

this project doesn't actually do anything with images

remove sorl+Pillow

---

pump/settings_shared.py
requirements.txt

remove typogrify

---

media/js/src/wizard.js

new version of JSCS has new things to complain about

make JSCS happy

---

pump/settings_shared.py
pump/templates/base.html
pump/urls.py
requirements.txt

remove django-registration, since this project doesn't actually use it
and 1.1 doesn't work with django 1.9

:arrow_up: Django 1.9.2

---

pump/templates/base.html

change header language

---

bdd_tests/features/wizard.feature
pump/templates/main/index.html

houghton question text changes

---

pump/templates/main/index.html

Text updates - Balance Test 2

---

bdd_tests/features/wizard.feature
pump/templates/main/index.html

ABCs text changes

---

pump/templates/main/index.html

balance test 1 text changes

---

bdd_tests/features/runthrough.feature
bdd_tests/steps/runthrough.py
pump/main/models.py
pump/main/tests/test_models.py
pump/templates/main/response_detail.html

switch to 'positive' language on results

---

pump/main/criteria.py
pump/main/tests/test_criteria.py

more granular scoring criteria for houghton

---

pump/templates/main/response_detail.html

add tips section to my results page

---

media/js/src/wizard.js
pump/main/views.py
pump/templates/main/index.html

collect and store the risk inventory questions. not displaying them yet.

risk inventory questions

---

pump/templates/main/index.html

add preamble

---

pump/templates/main/response_detail.html

add summary paragraph

---

.travis.yml
pump/main/tests/test_views.py
pump/settings.py
requirements.txt

Two package changes here:
* According to `pip show`, BeautifulSoup isn't a dependency of any other
packages in requirements.txt, and it caused a py3 error so I've
removed it.
* enum34 is listed twice in requirements.txt, so I've removed the
duplicate.

Test on python 3

---

pump/templates/main/index.html

Correct image include

---

pump/main/criteria.py
pump/main/tests/test_criteria.py
pump/main/tests/test_models.py
pump/templates/main/index.html

- Set the question scores to be 0 indexed, so they add up to 12
- Update the text, remove "ability"

PMT #114108 Section xiii

---

media/css/main.css
pump/templates/base.html
pump/templates/main/index.html
pump/templates/main/response_detail.html

Changes include:
- Increasing the baseline font size
- Narrowing the column for readability
- Adding space between elements, again for reabability
- Increasing the size of the site name for clarity

PMT #114273: Improve Layout

---

pump/templates/main/response_email.html

Also updates some text to match the existing score page.

PMT #116004: Improve email template style and features

---

pump/settings_staging.py

This got messed up during my sentry-sdk change.

Fix staging cloudfront path

---

.travis.yml
requirements.txt

update dependencies & remove iPython

Remove python 3.5 support

---

requirements.txt

Revert "build(deps): bump django-compressor from 3.1 to 4.0"

---

requirements.txt

Revert "⬆️ Bump django-storages from 1.13 to 1.14"
